/* eslint-disable prettier/prettier */
const avatar1 = process.env.REACT_APP_ASSETS_BUCKET + '/avatars/avatar1.webp';
const avatar2 = process.env.REACT_APP_ASSETS_BUCKET + '/avatars/avatar2.webp';
const avatar3 = process.env.REACT_APP_ASSETS_BUCKET + '/avatars/avatar3.webp';
const avatar4 = process.env.REACT_APP_ASSETS_BUCKET + '/avatars/avatar4.webp';

export interface GarlicEvents {
  _id: string;
  category: string;
  typeOfParticipant: string;
  garlickyFeature?: string;
  address: string;
  date?: string;
  city: string;
  postalCode?: string;
  email?: string;
  website?: string;
  insta?: string;
  hours?: string;
  streetAddress2?: string;
  tel?: string;
  facebook?: string;
  twitter?: string;
  otherSocialMedia?: string;
  details?: string;
  businessName: string;
  restaurant?: string;
  coordinate?: Array<number>;
}

export const getEvents = (): Promise<GarlicEvents[]> => {
  return new Promise((res) => {
    setTimeout(() => {
      res([
        {
          _id: '64f8a56405e2ac50b5e0edfb',
          category: 'Farm',
          businessName: 'Indian Creek Orchard Gardens',
          typeOfParticipant: 'Indian Creek Orchard Gardens',
          garlickyFeature:
            'Selling seed and culinary garlic, also our season end "Scratch and Dent" garlic sale will be taking place',
          details:
            'Selling seed and culinary garlic, also our season end scratch and dent garlic sale will be taking place',
          address: '919 Sugar Bush Road',
          date: 'Sept 23, Sept 28, Sept 30',
          city: 'Pakenham',
          postalCode: 'K0A2X0',
          tel: '(613) 914-7444',
          email: 'scott@indiancreekorchard.ca',
          website: 'www.indiancreekorchard.ca',
          facebook: 'https://www.facebook.com/indiancreekorchard',
          coordinate: [-76.287987, 45.335297],
        },
        {
          _id: '64f8a56405e2ac50b5e0edfc',
          category: 'Farm',
          businessName: 'Creation Farms ',
          typeOfParticipant: 'Creation Farms ',
          garlickyFeature:
            'We grow no-spray, hardneck variety, Music Garlic freshly cured ready for all your culinary adventures. We also have our much loved and potent Garlic Himalayan Pink Salt gourmet spice.',
          details:
            "Were at the Newmarket Farmers' Market every Saturday until October 1, and that runs between 8am-1pm. We hope to see you there!",
          address: 'Riverwalk Commons, 200 Doug Duncan Dr',
          date: 'Sept 23, 8am-1pm, Sept 30, 8am-1pm',
          city: 'Newmarket ',
          postalCode: 'L3Y 3Y9',
          tel: '905 478 1551 ',
          email: 'Creationfarmson@gmail.com',
          website: 'www.creationfarms.ca',
          facebook: 'N/a',
          insta: '@creationfarmsontario',
          twitter: 'N/a',
          otherSocialMedia: 'N/a',
          coordinate: [-79.457357, 44.055766],
        },
        {
          _id: '64f8a56405e2ac50b5e0edfd',
          category: 'Farm',
          businessName: 'Food 4 Life Market Garden',
          typeOfParticipant: 'Food 4 Life Market Garden',
          garlickyFeature:
            "Black garlic products: whole bulbs, sea salt, balsamic vinegar, powder. Regular garlic bulbs. Pickled garlic cloves. Garlic scapes: Pickled garlic scapes & cloves mix, sea salt, powder, We're also at St. Catharines Farmers market Sept 23 (7am-1pm).",
          details:
            'Black garlic products: whole bulbs, sea salt, balsamic vinegar, powder. Regular garlic bulbs. Pickled garlic cloves. Garlic scapes: Pickled garlic scapes & cloves mix, sea salt, powder',
          address: '215 Victoria Ave, Fenwick, ON, L0S 1C0 (all week 10am-4pm)',
          date: 'Sept 22-Oct 1, 10am-4pm',
          streetAddress2: 'St. Catherines Farmers Market: 91 King St. St. Catharines, ON, L2R (Sept 23: 7am-1pm) 3H6',
          city: 'Fenwick',
          postalCode: 'L0S 1C0',
          tel: '647 998 9887',
          email: 'info@food4lifemarket.com',
          website: 'www.food4lifemarket.com',
          facebook: 'www.facebook.com/food4lifemarketgarden',
          insta: '@food4lifemarketgarden',
          coordinate: [-79.386985, 43.023834],
        },
        {
          _id: '64f8a56405e2ac50b5e0edfe',
          category: "Famers' Market",
          businessName: "Waterdown Farmers' Market",
          typeOfParticipant: "Waterdown Farmers' Market",
          details:
            'We can highlight vendors that have garlic at our market on our social media. We can also plan to do a kids craft for market goers to make a magical garlic wand! ',
          address: 'Royal Canadian Legion Br. 551 ',
          date: 'Sept 30 (8am - 1 PM',
          streetAddress2: '79 Hamilton St. N',
          city: 'Waterdown',
          postalCode: 'L0R 2H0',
          tel: '289-260-6841',
          email: 'farmersmarket@waterdownvillage.ca',
          website: 'waterdownfarmersmarket.ca',
          facebook: 'https://www.facebook.com/waterdownfarmersmarket',
          insta: 'https://www.instagram.com/waterdownfarmersmarket/',
          twitter: 'https://twitter.com/WaterdownMarket',
          coordinate: [-79.904558, 43.338754],
        },
        {
          _id: '64f8a56405e2ac50b5e0edff',
          category: 'Restaurant',
          businessName: 'Beefcake’s Burger Factory',
          typeOfParticipant: 'Beefcake’s Burger Factory',
          garlickyFeature: 'Garlic Havarti Burger',
          details: 'Garlic Havarti Burger',
          address: '481 Hodder Avenue',
          date: 'Sept 22-Oct 1',
          city: 'Thunder Bay ',
          postalCode: 'P7A1V3',
          tel: '8076301640',
          email: 'Beefcakesburgerfactory@gmail.com',
          website: 'www.beefcakesburgerfactory.com',
          facebook: 'Beefcakes Burger Factory ',
          insta: '@beefcakeburgerstbay',
          twitter: '@beefcakeburger ',
          coordinate: [-89.182726, 48.468417],
        },
        {
          _id: '64f8a56405e2ac50b5e0ee00',
          category: 'Restaurant',
          businessName: 'Barrel Restaurant',
          typeOfParticipant: 'Barrel Restaurant',
          garlickyFeature: 'Garlic bread',
          details: 'sell garlic bread',
          address: '131 Queensway West ',
          date: 'Sept 22-Oct 1',
          city: 'Simcoe',
          postalCode: 'N3Y2M8',
          tel: '519 426 0068',
          email: 'info@barrelrestaurant.ca',
          website: 'www.barrelrestaurant.ca',
          facebook: 'barrelrestaurantsimcoe',
          insta: 'barrelpizzaspaghettihouse',
          twitter: '@Barrel87',
          coordinate: [-80.312449, 42.845631],
        },
        {
          _id: '64f8a56405e2ac50b5e0ee02',
          category: "Farmers' Market",
          businessName: "Port Rowan Farmers' Market",
          typeOfParticipant: "Port Rowan Farmers' Market",
          garlickyFeature: 'We have a few vendors with their homegrown garlic.  ',
          details:
            "We have a few vendors with their homegrown garlic.  Not sure - might ask bakery to do 'garlic' themed food, or run a contest.  ",
          address: 'Lions Pavilion in Port Rowan Harbour',
          date: 'Sept 22, Sept 29',
          streetAddress2: '11 Sea Queen Rd.',
          city: 'Port Rowan',
          postalCode: 'N0E 1M0',
          tel: '519-586-9532',
          email: 'portrowanfarmersmarket@gmail.com',
          website: 'www.portrowanfarmersmarket.ca',
          facebook: 'https://www.facebook.com/PortRowanFarmersMarket',
          insta: "portrowanfarmersmarket's profile picture portrowanfarmersmarket",
          twitter: 'none',
          coordinate: [-80.44, 42.6],
        },
        {
          _id: '64f8a56405e2ac50b5e0ee03',
          category: 'Restaurant',
          businessName: 'Fringale',
          typeOfParticipant: 'Fringale',
          garlickyFeature: 'Garlicky details to be anniunced',
          details: 'Not sure yet. ',
          address: '1177 Queen St. East (Radical Road)',
          date: 'Sept 22-Oct 1',
          city: 'Toronto',
          postalCode: 'M4M 1L5',
          tel: '416-206-1289',
          email: 'hi@jefringale.ca',
          website: 'jefringale.ca',
          facebook: 'https://www.facebook.com/jefringale',
          insta: '@jefringale',
          coordinate: [-79.332722, 43.662567],
        },
        {
          _id: '64f8a56405e2ac50b5e0ee04',
          category: "Farmers' Market",
          businessName: "Orillia Farmers' Market",
          typeOfParticipant: "Orillia Farmers' Market",
          details: 'not sure',
          address: '36 Mississaga Street W',
          city: 'Orillia',
          postalCode: 'L3V 3A6',
          tel: '705-238-7955',
          email: 'dsmith@orillia.ca',
          website: 'www.orillia.ca/ofm',
          facebook: 'https://www.facebook.com/orilliafarmersmarket',
          insta: 'https://www.instagram.com/orilliafarmersmarket/',
          coordinate: [-79.420003, 44.608341],
        },
        {
          _id: '64f8a56405e2ac50b5e0ee05',
          category: 'Farm',
          businessName: 'Count Von Garlic',
          typeOfParticipant: 'Count Von Garlic',
          details: 'Selling garlic',
          address: 'Our Property',
          streetAddress2: '52 Church Street West',
          city: 'Burgessville',
          postalCode: 'N0J1C0',
          tel: '226747659',
          email: 'sales@countvongarlic.com',
          website: 'https://countvongarlic.com/',
          twitter: '@CountVonGarlic',
          coordinate: [-80.68, 43],
        },

        {
          _id: '64f8a56405e2ac50b5e0ee0a',
          category: 'Special Activity',
          businessName: 'Brant County Garlic Company Inc',
          typeOfParticipant: 'Brant County Garlic Company Inc',
          garlickyFeature: 'Mentor New Growers and Gardeners. ',
          details: 'Mentor New Growers and Gardeners',
          address: '298 13th Concession Road',
          date: 'Sept 22-Oct 1, 7am-8pm',
          city: 'Scotland',
          postalCode: 'N0E 1R0',
          tel: '519-751-9200',
          email: 'bob@brantcountygarliccompany.com',
          website: 'www.brantcountygarliccompany.com',
          facebook: 'Brant County Garlic Company',
          coordinate: [-80.28, 43.02],
        },

        {
          _id: '64f8a56405e2ac50b5e0ee0b',
          category: 'Independent Grocer',
          businessName: 'salt + MUSTARD',
          typeOfParticipant: 'salt + MUSTARD',
          garlickyFeature:
            'We have our black garlic products available as well as we will be hosting a farmer to sell their garlic. Details  to be anniunced',
          details:
            'We will have our black garlic products available as well as we will be hosting a farmer to sell their garlic.',
          address: '335 Jane St. Toronto',
          city: 'Toronto',
          postalCode: 'M6S 3E4',
          tel: '6472188640',
          email: 'hello@saltnmustard.com',
          website: 'www.saltnmustard.com',
          insta: '@saltnmustard',
          coordinate: [-79.472965, 43.64163],
        },

        {
          _id: '64f8a56405e2ac50b5e0ee08',
          category: "Farmers' Market",
          businessName: "Minto Farmers' Market",
          typeOfParticipant: "Minto Farmers' Market",
          details:
            'not totally sure yet but we plan to have a fall themed craft. Last year we did guess the weight of a pumpkin so maybe guess the weight of three garlics to win them.',
          address: 'Palmerston Railway Heritage Museum',
          streetAddress2: ' 164 William St',
          city: 'Palmerston',
          postalCode: 'N0G 2P0',
          tel: '519-338-2511 ext 242',
          email: 'erin@town.minto.on.ca',
          website: 'mintofarmersmarket.ca',
          facebook: '@MintoFarmersMarket',
          insta: '@MintoFarmersMarket',
          twitter: 'N/a',
          coordinate: [-80.84, 43.84],
        },
        {
          _id: '64f8a56405e2ac50b5e0ee01',
          category: 'Restaurant',
          businessName: "Pancer's Original Deli",
          typeOfParticipant: "Pancer's Original Deli",
          garlickyFeature: 'Corned beef cooked with Ontario garlic ',
          details: 'Corned beef cooked with Ontario garlic ',
          address: '3856 Bathurst St.',
          date: 'Sept 22-Oct 1',
          city: 'Toronto ',
          postalCode: 'M3H 3N3',
          tel: '9412245369',
          email: 'Pancersoriginal@gmail.com',
          website: 'Pancersoriginaldeli.com',
          coordinate: [-79.435315, 43.740986],
        },
        {
          _id: '64f8a56405e2ac50b5e0ee09',
          category: "Farmers' Market",
          businessName: "Cabbagetown Farmers' Market",
          typeOfParticipant: "Cabbagetown Farmers' Market",
          garlickyFeature:
            'We are highlighting our garlic farmers and other vendors who prepare goods made with Ontario garlic.',
          details:
            "We're a weekly farmers' market in the Cabbagetown neighbourhood. We will be highlighting our garlic farmers and other vendors who prepare goods made with garlic. We might be doing a roasted garlic workshop/tasting but still in the works. ",
          address: '191 Winchester St',
          date: 'Sept 27, 3-7pm',
          city: 'Toronto',
          postalCode: 'M4X 1B8',
          tel: '705-331-2870',
          email: 'ellie@cabbagetownmarket.ca',
          facebook: "Cabbagetown Farmers' Market",
          insta: '@cabbagetownmarket',
          coordinate: [-79.359252, 43.667625],
        },
        {
          _id: '64f8a56405e2ac50b5e0edfa',
          category: 'Farm',
          businessName: 'Flycreek farm',
          typeOfParticipant: 'Flycreek farm',
          garlickyFeature: 'Farm stand garlic sales, for culinary use and seed.',
          details: 'Farm stand garlic sales, culinary and seed.',
          address: '9887 flycreek rd, ',
          date: 'Sept 22-Oct1',
          city: 'North augusta',
          postalCode: 'K0g1r0 ',
          tel: '6132461884',
          email: 'Brandyjackson1@gmail.com',
          website: 'Flycreekfarm.ca',
          insta: 'Flycreek_farm',
          coordinate: [-75.77, 44.71],
        },
        {
          _id: '64f8a56405e2ac50b5e0ee06',
          category: 'Farm',
          businessName: "EPO ALPHONSAS GOURMET INC at Erin Mills Farmers' Market",
          typeOfParticipant: "EPO ALPHONSAS GOURMET INC at Erin Mills Farmers' Market",
          garlickyFeature: 'Garlic jelly ',
          details: 'Garlic Jelly .. ',
          address: '2520 Eglinton Ave West',
          date: 'Sept 29, Oct 1',
          city: 'Mississagua',
          tel: '416 558 5791',
          email: 'alphonsas@rogers.com',
          website: 'www.alphonsas.ca',
          facebook: 'https://www.facebook.com/alphonsasgourmet',
          insta: 'https://www.instagram.com/alphonsasgourmet/',
          coordinate: [-78.346464, 44.699869],
        },
        {
          _id: '64f8a56405e2ac50b5e0ee07',
          category: "Farmers' Market, Special Activity",
          businessName: 'City of St. Catharines',
          typeOfParticipant: 'City of St. Catharines',
          garlickyFeature:
            'On the Market Discovery Table, we are featuring a local garlic farmer along with a hostess offering a garlic themed craft for the young ones, free garlic focused recipes and sharing information on the health benefits of garlic, where it originated, and how it is grown.',
          details:
            'On the Market Discovery Table, we will be featuring a local garlic farmer along with a hostess offering a garlic themed craft for the young ones, free garlic focuses recipes and educational components of the health benefits of garlic, where is originated and how it is grown.',
          address: '91 King St. ',
          date: 'Sept 23, 7am-1pm',
          city: 'St. Catharines',
          postalCode: 'L2R 7C2',
          tel: '905-932-0639',
          email: 'dchakarova@stcatharines.ca',
          website: 'www.stcatharines.ca/marketevents',
          facebook: 'https://www.facebook.com/VendorsSt.CatharinesFM',
          insta: 'https://www.instagram.com/stc_farmmarketvendors/',
          coordinate: [-79.24831, 43.15855],
        },
        {
          _id: '64f8a56405e2ac50b5e0ee0c',
          category: 'Restaurant, Special Activity',
          businessName: 'Black Dog Bistro',
          typeOfParticipant: 'Black Dog Bistro',
          garlickyFeature: 'Giveaway',
          details:
            'In the restaurant it will be an appetizer, during taste of Manotick, the giveaway will also probably be an appetizer with garlic decor.',
          address: '5540 Manotick Main Street, Manotick, Ontario',
          date: 'Sept 23, 2pm-8pm',
          city: 'Manotick, the south part of Ottawa',
          postalCode: 'K4M 1A6',
          tel: '613 692-3779',
          email: 'blackdogbistro@bellnet.ca',
          website: 'www.blackdogbistro',
          facebook: 'Dot JANZ',
          insta: 'Black Dog Bistro',
          coordinate: [-75.68667, 45.22516],
        },
      ]);
    }, 10);
  });
};
